HOST = "127.0.0.1"
PORT = 22222
SERVER_ADDRESS = (HOST, PORT)
BUFSIZE = 1024

SIGNAL_NICKNAME = "NICK"
B_SIGNAL_NICKNAME = b"NICK"
SIGNAL_WELCOME = "WELCOME"
B_SIGNAL_WELCOME = b"WELCOME"
SIGNAL_STOP = "STOP"
B_SIGNAL_STOP = b"STOP"
