"""added todo.description

Revision ID: 70027e601bbf
Revises: 
Create Date: 2023-11-05 20:17:45.951235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70027e601bbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
