"""added M2M Post<>Tab

Revision ID: b0b54c2b19c1
Revises: 0f79c2d12d8e
Create Date: 2023-12-11 15:27:39.344118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b54c2b19c1'
down_revision = '0f79c2d12d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_post_tag_m2m_post_id'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_post_tag_m2m_tag_id'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    # ### end Alembic commands ###
